### ISSUE TITLE
Fixing some possibles problems with the install and run

### ISSUE THREAD

**Issue by O-Rocha** [angular-cms/angular-cms#117]
Hi I'm very interested in this project, but i ran into some problems while trying to run it, so I suggested a few changes and made some fixes that may help, and would like to make a pull request if that's ok.

**Comment by danghung1202** [comment]
Hi @O-Rocha, 

Thank you for posting this issue. It is better and helpful for me if you can has more detail about this issue :)

Feel free to make a pull request and contribute. I will review now.

Thank you for your contributes

/hung.dang
