### ISSUE TITLE
API and Server issue (installation) - fix

### ISSUE THREAD

**Issue by GuilhermeHdAS** [angular-cms/angular-cms#119]
Hello, very cool your project.

I had a problem when installing with the server and the API, the correction used was:

In the folder **"cms-api"** the file **"package.json"** creates an API with **"version: 1.0.0"** and in **"package-lock.json"** also:

```
package.json:
{
   "name": "@ angular-cms / api",
   "version": "1.0.0",
...

```
```
package-lock.json:
{
   "name": "@ angular-cms / api",
   "version": "1.0.0",
...
```

However, in the server folder, "cms-server" is:

```
package.json:
"dependencies": {
     "@angular-cms/api": "0.0.1",
...
```

```
package-lock.json:
{
   "name": "cms-server",
   "version": "0.0.1",
   "lockfileVersion": 1,
   "requires": true,
   "dependencies": {
     "@ angular-cms / api": {
       "version": "0.0.1"
...
```

And the change I made was in the **"cms-api" folder**, putting the API version as 0.0.1 in **"package.json" and "package-lock.json"**, like this:

```
package.json:
{
   "name": "@ angular-cms / api",
   "version": "0.0.1",
...
```

```
package-lock.json:
{
   "name": "@ angular-cms / api",
   "version": "0.0.1",
...
```

Your project is very cool!

**Comment by GuilhermeHdAS** [comment]
I made a pull request with the changes I made to a feature branch (feature / correction-api-version) comparing it to dev, I also changed README.md, adding a command.

**Comment by danghung1202** [comment]
Hi @GuilhermeHdAS 

First of all, thank you so much for your comments.

I'm actually happy with your interesting for my project. Basically, this project still is working on progress and has not any release yet. For now, it has a lot of issue, major tasks which need to done. I hope I can make a first release in the end of this year. (The promise by me :)). In first release, we will have the document, demo site and offical AngularCms site. 

Keep your eyes on this project and feel free to make the pull request for new features, issues...

If you have any question about this project, send me a mail to danghung1202@gmail.com

Thanks
/Hung.dang

**Comment by danghung1202** [comment]
Merged your pull request, thanks

**Comment by GuilhermeHdAS** [comment]
Hi @danghung1202 

Thank you for accepting the pull request and it is an honor to be able to collaborate on this project.

A lot of success for you!
