### ISSUE TITLE
ERROR in cms-demo/src/app/app-routing.module.ts:3:85 - error TS2307: Cannot find module '@angular-cms/core'.

### ISSUE THREAD

**Issue by priyesh-975** [angular-cms/angular-cms#125]
i am getting most of error in @angular-cms/core

**Comment by danghung1202** [comment]
HI @priyesh-975 , sorry for late answer. 
Could you fork the latest source code and follow these steps to install

[https://github.com/angular-cms/angular-cms#how-to-run-in-dev-mode](https://github.com/angular-cms/angular-cms#how-to-run-in-dev-mode)

Thanks
