### ISSUE TITLE
Error: Cannot find module '@angular-cms/api'

### ISSUE THREAD

**Issue by harsh9090** [angular-cms/angular-cms#138]
when I tried **npm run dev** in the cms-server folder the data in node_modules -> @anguar-cms/API got erased and that's why it is giving me the error. How to resolve it. can you guide me?

**Comment by danghung1202** [comment]
Hi @harsh9090 , sorry for late response.

Did you setup the npm symlinks as this link?
https://github.com/angular-cms/angular-cms#setup-npm-symlinks

When you done the above setup, following the step
https://github.com/angular-cms/angular-cms#run-in-dev-mode

> If you have the issue installing such as the @angular-cms/api package is not found, temporary remove it in package.json, run install command then add it again

Thanks

**Comment by harsh9090** [comment]
Yes, I have followed all the steps. Still getting the error.

**Comment by danghung1202** [comment]
hi @harsh9090 , sorry for late response, I'm very busy on some stuffs.

Could you try again following these steps:

1. Under the cms_api folder, delete the node_modules folder, delete the package-lock.json and run `npm install` then run `npm link` then run `npm run build`
2. Under the cms_server folder, delete the node_modules folder,  package-lock.json then run `npm install` then `npm link @angular-cms/api` and then `npm run dev`

> If you have the issue installing such as the @angular-cms/api package is not found, temporary remove it in package.json, run install command then add it again
