### ISSUE TITLE
[Error install] Error when install sharp 

### ISSUE THREAD

**Issue by ngnam** [angular-cms/angular-cms#90]
Error when install sharp.
```
> sharp@0.23.4 install E:\work_company\angular-cms\cms-api\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
```

https://github.com/lovell/sharp/issues/1539

**Comment by danghung1202** [comment]
Hi @ngnam , thank you for reporting this issue.

I've tried clone and run npm install, everything is fine, the sharp package is dowloaded and installed successfully. I'm using the node v12.14.1

`> sharp@0.23.4 install D:\Git\angular-cms-v9\cms-api\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-win32-x64.tar.gz
info sharp Creating D:\Git\angular-cms-v9\cms-api\node_modules\sharp\build\Release
info sharp Copying DLLs from D:\Git\angular-cms-v9\cms-api\node_modules\sharp\vendor\lib to D:\Git\angular-cms-v9\cms-api\node_modules\sharp\build\Release`

Could you try?

/hung.dang
